### ISSUE TITLE
macOS - Ctrl-F5 (mouse-lock) locks SheepShaver

### ISSUE THREAD

**Issue by emendelson** [cebix/macemu#144] opened 2017-11-22 14:35 UTC
As far as I can tell, after building the current SheepShaver code under Xcode 9, Ctrl-F5 (which locks the mouse) causes SheepShaver to lock entirely; it can only be shut down with Ctrl-Esc.

EDIT: I've found this problem in two separate High Sierra systems. Ronald at emaculation.com reports that the problem does NOT occur under Sierra.

**Comment by RonaldPR** [comment] 2017-11-23 19:40
Unlike what I wrote at first at emaculation.com, it seems that the issue exists also in Sierra, at least something very similar. After locking the mouse cursor inside the window using Ctrl-F5, SheepShaver seems unresponsive to mouse clicks and thus seems locked. But what appears to be the case is that SheepShaver does not know where the arrow cursor is inside the window. With random clicking multiple times in various positions, sometimes an object in a different position inside the window reacts as if it is clicked on. Again using Ctrl-F5 to unlock the mouse cursor, returns behaviour to normal.

SheepShaver builds created almost 4 years ago do not have this issue. What could have been changed since then that affects mouse cursor position?

**Comment by asvitkine** [comment] 2017-11-24 00:35
It's certainly possible. You can try building SheepShaver at intermediate
revisions between current tip of tree and 4 years ago to narrow down to
when it broke.

**Comment by RonaldPR** [comment] 2017-11-24 19:28
I traced the issue back to merged pull request #112 from dmac100/relative_mouse (SDL: Use relative mouse values when grabbed.), committed on July 21. After reversing the changes made in BasiliskII/src/SDL/video_sdl.cpp, the resulting SheepShaver build does not show this issue anymore.

**Comment by emendelson** [comment] 2017-11-25 02:35
I wish I had the same experience! I still see the problem after reversing those changes...

**Comment by RonaldPR** [comment] 2017-11-25 08:26
It works fine here in Sierra with respect to the Ctrl-F5 issue.

(The only remaining issue is the initial blank screen after using Ctrl-return for changing between window and full-screen mode before any mouse clicks were made. May also be something SDL-related)

Apparently there are more problems involved for the issue in High Sierra.

**Comment by asvitkine** [comment] 2017-11-25 14:31
I am able to reproduce the issue with pull request #112
<https://github.com/cebix/macemu/pull/112> and can see it gone with it
reverted - on Sierra. Will revert that change. Thanks for diagnosing the
issue!

**Comment by emendelson** [comment] 2017-11-25 23:12
@asvitkine - The fix works under High Sierra too. Thank you!

**Closed** 2017-12-02 19:03 UTC
